# Generated by Django 2.1.7 on 2019-07-22 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 22, 44, 25, 112976), verbose_name='date published'),
        ),
    ]
